BINARY := meetap

WHISPER_VERSION := v1.8.4
WHISPER_SRC := $(CURDIR)/.whisper-cpp
WHISPER_BUILD := $(WHISPER_SRC)/build

LIB_DIR := $(WHISPER_BUILD)/lib
INCLUDE_DIR := $(WHISPER_BUILD)/include

VERSION := $(shell git describe --tags --always --dirty 2>/dev/null || echo "dev")
COMMIT := $(shell git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_DATE := $(shell date -u +%Y-%m-%d)
GO_LDFLAGS := -X github.com/marimelon/meetap/cmd.Version=$(VERSION) \
              -X github.com/marimelon/meetap/cmd.Commit=$(COMMIT) \
              -X github.com/marimelon/meetap/cmd.BuildDate=$(BUILD_DATE)

export CGO_LDFLAGS := -L$(LIB_DIR) -lwhisper -lggml -lggml-base -lggml-cpu -lggml-metal -lggml-blas -framework Accelerate -framework Metal -framework Foundation -framework CoreGraphics -lstdc++ -lm
export C_INCLUDE_PATH := $(INCLUDE_DIR)

.PHONY: build clean clean-all libs licenses

build: libs
	go build -ldflags '$(GO_LDFLAGS)' -o $(BINARY) .

libs: $(LIB_DIR)/libwhisper.a

$(LIB_DIR)/libwhisper.a:
	@echo "Building whisper.cpp $(WHISPER_VERSION)..."
	git clone --depth 1 --branch $(WHISPER_VERSION) https://github.com/ggml-org/whisper.cpp.git $(WHISPER_SRC)
	cmake -B $(WHISPER_BUILD)/cmake -S $(WHISPER_SRC) \
		-DCMAKE_BUILD_TYPE=Release \
		-DBUILD_SHARED_LIBS=OFF \
		-DGGML_METAL=ON \
		-DGGML_BLAS=ON \
		-DWHISPER_BUILD_EXAMPLES=OFF \
		-DWHISPER_BUILD_TESTS=OFF
	cmake --build $(WHISPER_BUILD)/cmake --config Release -j$$(sysctl -n hw.ncpu)
	@mkdir -p $(LIB_DIR) $(INCLUDE_DIR)
	cp $(WHISPER_BUILD)/cmake/src/libwhisper.a $(LIB_DIR)/
	cp $(WHISPER_BUILD)/cmake/ggml/src/libggml.a $(LIB_DIR)/
	cp $(WHISPER_BUILD)/cmake/ggml/src/libggml-base.a $(LIB_DIR)/
	cp $(WHISPER_BUILD)/cmake/ggml/src/libggml-cpu.a $(LIB_DIR)/
	cp $(WHISPER_BUILD)/cmake/ggml/src/ggml-metal/libggml-metal.a $(LIB_DIR)/
	cp $(WHISPER_BUILD)/cmake/ggml/src/ggml-blas/libggml-blas.a $(LIB_DIR)/
	cp $(WHISPER_SRC)/include/whisper.h $(INCLUDE_DIR)/
	cp $(WHISPER_SRC)/ggml/include/ggml*.h $(INCLUDE_DIR)/

licenses: libs
	@echo "Collecting licenses..."
	@echo "# Third-Party Licenses" > THIRD_PARTY_LICENSES
	@echo "" >> THIRD_PARTY_LICENSES
	@echo "## Go dependencies" >> THIRD_PARTY_LICENSES
	@echo "" >> THIRD_PARTY_LICENSES
	@go-licenses report ./... 2>/dev/null | grep -v "$(shell go list -m)" >> THIRD_PARTY_LICENSES
	@echo "" >> THIRD_PARTY_LICENSES
	@echo "## C/C++ dependencies" >> THIRD_PARTY_LICENSES
	@echo "" >> THIRD_PARTY_LICENSES
	@echo "whisper.cpp ($(WHISPER_VERSION)),https://github.com/ggml-org/whisper.cpp,MIT" >> THIRD_PARTY_LICENSES
	@echo "" >> THIRD_PARTY_LICENSES
	@echo "Generated by: make licenses"

clean:
	rm -f $(BINARY)

clean-all: clean
	rm -rf $(WHISPER_SRC)
